# -*- coding: utf-8 -*-

# ディレクトリ定義
LIBRARY_LICENSE_DIR = "./lib_license/"
DDL_DIR = "./ddl/"
FONT_DIR = "./fonts"
FONT_FILE_NAME = "Corporate-Mincho-ver2.otf"

# DBのバージョン
DB_VERSION_05 = "v0.5"
DB_VERSION_08 = "v0.8"
DB_VERSION_09 = "v0.9"

CURRENT_DB_VERSION = DB_VERSION_09
OLD_DB_VERSION_LIST = [DB_VERSION_05, DB_VERSION_08]

DB_SUCCESS = 0
DB_UPDATE = 1
DB_ERROR_FILE_BREAK = -1
DB_ERROR_UNKNOWN_FILE = -2