name: Action Sample

on:
  - pull_request

jobs:
  package:
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Package Application
        run: |
          python -m pyinstaller testcon.spec


      - name: upload Package
        uses: actions/upload-artifact@v2
        with:
          name: name-of-artifact
          path: src/dist/windows
