name: Action Sample

on:
  - pull_request

jobs:
  conda-test:
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - name: Install 7zip
        run: choco install 7zip.install
      - name: Install Mesa
        shell: cmd
        run: |
          curl.exe -L --output mesa.7z --url https://github.com/pal1000/mesa-dist-win/releases/download/20.3.2/mesa3d-20.3.2-release-msvc.7z
          "C:\Program Files\7-Zip\7z.exe" x mesa.7z
          mklink opengl32.dll "x64\opengl32.dll"
          mklink libglapi.dll "x64\libglapi.dll"
        working-directory: build\tests\Debug
      - name: Setup Python
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: ./setup.yml
          auto-activate-base: false
          auto-update-conda: true
          use-only-tar-bz2: true
          channels: conda-forge
          channel-priority: true
    
      - name: conda lib List
        run: conda list

      - name: PyTest
        run: |
          python -m pytest --junit-xml ./pytest.xml | tee ./pytest-coverage.txt
        continue-on-error: true
  
      # テスト結果をプルリクにコメントする
      - name: Pytest coverage comment
        if: always()
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: results/pytest-coverage.txt
          junitxml-path: results/pytest.xml

      - name: pyinstaller package
        run: pyinstaller testcon.spec

      - uses: actions/upload-artifact@v2
        with:
          name: name-of-artifact
          path: src/dist
