name: Action Sample

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  numpy-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
      - uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: ./setup.yml
        auto-activate-base: false
        auto-update-conda: true
        use-only-tar-bz2: true