name: Action Sample

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  conda-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: ./setup.yml
          auto-activate-base: false
          auto-update-conda: true
          use-only-tar-bz2: true
          channels: conda-forge
          channel-priority: true
    
      - name: conda lib List
        run: conda list
      
      - name: python version
        run: python --version

      - name: PyTest
        run: |
          python -m pytest test --junit-xml results/pytest.xml
        continue-on-error: true

      # テスト結果の表示
      - name: Upload Unit Test Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: Unit Test Results (Python 3.7)
          path: results/*.xml

      - name: Download Artifacts
        if: success() || failure()
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          junit_files: artifacts/**/*.xml
